Testing entry ejs
Eazy-Sneezy/Testing pull request #24
Opened 2021-05-04 21:20 UTC by ryanboothforever

A better looking Entry EJS.  I will come back and fix the like/delete in a bit.

2021-05-04 21:38 UTC, AngelGDev commented
Looks good. I'd like it to have a link to go back to the feed, a space to display the caption of the entry, and maybe the blue banner on top to be more consistent with the rest of the app

2021-05-04 21:49 UTC, laylar commented
![Screen Shot 2021-05-04 at 2 47 51 PM](https://user-images.githubusercontent.com/10251025/117074130-cc4db680-ace7-11eb-8c1a-164f9ce03cfd.png)
This is what I see on the profile page on the testingEntryEjs branch. Is that what it's supposed to look like? If so, I think this is ready to merge.

2021-05-05 00:59 UTC, laylar requested changes
This actually breaks it. It was working with "entries" before because it is looping through entries, now it's trying to loop through "entry".

2021-05-05 01:05 UTC, laylar requested changes
I went in and suggested the specific lines where the edits should be. Mostly trying out that functionality, I think you'll know what I mean when you see the previous comment.

2021-05-05 01:05 UTC, laylar commented on views/feed.ejs
> +        </li>
```suggestion
        <% for(var i=0; i<entries.length; i++) {%>
        <li class="card">
          <div class="entry-topper">
            <div class="entry-title">
              <p><%= entries[i].title%></p>
            </div>
            <div class="entry-author">
              <p>By: <%= entries[i].author%></p>
            </div>
          </div>
          <a href="/entries/<%= entries[i]._id%>">
            <img class="feed-img" src="<%= entries[i].image%>">
          </a>
          <div>
            <span class="fa fa-heart"></span>
            <span><%= entries[i].likeCount %></span>
          </div>
        </li>
```

2021-05-05 01:12 UTC, AngelGDev commented
Inside feed.ejs we use entries[i].<property> while looping through the array.
Inside entry.ejs we use entry.<property>.

Sorry if I didn't make that clear before

2021-05-05 16:36 UTC, merged